apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: petclinic

resources:
  # --- Deployments ---
  - deployments/config-server.yaml
  - deployments/discovery-server.yaml
  - deployments/api-gateway.yaml
  - deployments/admin-server.yaml
  - deployments/customers-service.yaml
  - deployments/visits-service.yaml
  - deployments/vets-service.yaml
  # - deployments/genai-service.yaml

  # --- Services ---
  - services/config-server.yaml
  - services/discovery-server.yaml
  - services/api-gateway.yaml
  - services/admin-server.yaml
  - services/customers-service.yaml
  - services/visits-service.yaml
  - services/vets-service.yaml
  - services/genai-service.yaml

  # --- Others ---
  - nginx-ingress.yaml
  - genai-secret.yaml
  - configmaps/boot-admin-client.yaml

  # --- HPA ---
  - hpa/hpa-all.yaml
